name: PR Template Validation

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR Body and Write to File
        id: get_pr_body
        run: |
          # Use printf para garantir que o conteúdo seja gravado literalmente
          # e remova os retornos de carro ao mesmo tempo
          printf "%s" "${{ github.event.pull_request.body }}" | tr -d '\r' > pr_body.txt
        shell: bash

      - name: Validate PR Description
        run: |
          PR_BODY=$(cat pr_body.txt)
          
          if echo "$PR_BODY" | grep -q "## Descrição" && ! echo "$PR_BODY" | grep -q "## Descrição\n\n[[:space:]]*[^[:space:]]"; then
            echo "::error file=.github/pull_request_template.md::A seção '## Descrição' não deve estar vazia. Por favor, adicione uma descrição."
            exit 1
          fi
        shell: bash

      - name: Validate PR Type Checklist
        run: |
          PR_BODY=$(cat pr_body.txt)
          if ! echo "$PR_BODY" | grep -q "## Tipo de Mudança" || ! echo "$PR_BODY" | grep -A 5 "## Tipo de Mudança" | grep -q "-\\[x\\]"; then
            echo "::error file=.github/pull_request_template.md::Pelo menos um tipo de mudança deve ser selecionado no checklist 'Tipo de Mudança'."
            exit 1
          fi
        shell: bash

      - name: Validate General Checklist
        run: |
          PR_BODY=$(cat pr_body.txt)
          if echo "$PR_BODY" | grep -q "## Checklist" && echo "$PR_BODY" | grep -A 10 "## Checklist" | grep -q "-\\[ \\]"; then
            echo "::error file=.github/pull_request_template.md::Alguns itens do 'Checklist' não foram marcados. Por favor, marque todos os itens relevantes."
            exit 1
          fi
        shell: bash
